# 워크 플로우의 이름 지정
name: Main_Workflows

# 워크 플로우의 특징 지정
# develop 브랜치 대상 PR이 생성되거나 변경될 때 실행
on:
  pull_request:
    branches:
      - main # pr 도착지

# job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "test"